name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # tu peux mettre une autre branche si tu veux

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
   
    - name: echo secrets 
      run: echo ${{ secrets.DOCKER_USERNAME }} ${{ secrets.DOCKER_PASSWORD }}

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/monapp:latest .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/monapp:latest
